name: Continuous Integration

on:
  push:
    branches:
      - main
      - develop
      - 'feat/**'
      - 'fix/**'
      - 'refactor/**'
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # .NET Backend Steps
    - name: Setup .NET 9.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore Backend Dependencies
      run: dotnet restore backend/ToDoList.Api/ToDoList.Api.csproj

    - name: Build Backend
      run: dotnet build backend/ToDoList.Api/ToDoList.Api.csproj --no-restore

    - name: Test Backend
      run: echo "Backend tests not implemented yet"

    # Node.js Frontend Steps
    - name: Setup Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: frontend/todolist-ui/package-lock.json

    - name: Restore Frontend Dependencies
      run: npm install --prefix frontend/todolist-ui

    - name: Lint Frontend
      run: npm run lint --prefix frontend/todolist-ui

    - name: Format Check Frontend
      run: npm run format:check --prefix frontend/todolist-ui

    - name: Build Frontend
      run: npm run build --prefix frontend/todolist-ui

    - name: Test Frontend
      run: npm test -- --watch=false --browsers=ChromeHeadless --prefix frontend/todolist-ui
